import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { HelloGrammarGeneratedModule, HelloGrammarGeneratedSharedModule } from './generated/module';
import { HelloGrammarValidator, registerValidationChecks } from './hello-grammar-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type HelloGrammarAddedServices = {
    validation: {
        HelloGrammarValidator: HelloGrammarValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type HelloGrammarServices = LangiumServices & HelloGrammarAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const HelloGrammarModule: Module<HelloGrammarServices, PartialLangiumServices & HelloGrammarAddedServices> = {
    validation: {
        HelloGrammarValidator: () => new HelloGrammarValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createHelloGrammarServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    HelloGrammar: HelloGrammarServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        HelloGrammarGeneratedSharedModule
    );
    const HelloGrammar = inject(
        createDefaultModule({ shared }),
        HelloGrammarGeneratedModule,
        HelloGrammarModule
    );
    shared.ServiceRegistry.register(HelloGrammar);
    registerValidationChecks(HelloGrammar);
    return { shared, HelloGrammar };
}
